parameters:
services:
  striide_twitter_bootstrap.twig.form.extension:
    class: Striide\TwitterbootstrapBundle\Extension\FormExtension
    tags:
      - { name: twig.extension }
  
  striide_twitter_bootstrap.twig.modal.extension:
    class: Striide\TwitterbootstrapBundle\Extension\ModalExtension
    arguments: [@twig]
    tags:
      - { name: twig.extension }